name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "650f9279da370cf492d1dbd21137728868d54a2f687efd73c3334de08bf3babc"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
