name = "Vinegar Modpack"
author = "Vinegar Community"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2972b493bdb8029026c7ae83b753127f6459ad2ab3c467e0e9899ebab0ac5eb"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"
